apps/note/api/urls.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from .views import NotePolymorphicViewSet, AliasViewSet, \
    TemplateCategoryViewSet, TransactionViewSet, TransactionTemplateViewSet


def register_note_urls(router, path):
    """
    Configure router for Note REST API.
    """
    router.register(path + '/note', NotePolymorphicViewSet)
    router.register(path + '/alias', AliasViewSet)

    router.register(path + '/transaction/category', TemplateCategoryViewSet)
    router.register(path + '/transaction/transaction', TransactionViewSet)
    router.register(path + '/transaction/template', TransactionTemplateViewSet)

apps/note/urls.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import path

from . import views
from .models import Note

app_name = 'note'
urlpatterns = [
    path('transfer/', views.TransactionCreate.as_view(), name='transfer'),
    path('buttons/create/', views.TransactionTemplateCreateView.as_view(), name='template_create'),
    path('buttons/update/<int:pk>/', views.TransactionTemplateUpdateView.as_view(), name='template_update'),
    path('buttons/', views.TransactionTemplateListView.as_view(), name='template_list'),
    path('consos/', views.ConsoView.as_view(), name='consos'),

    # API for the note autocompleter
    path('note-autocomplete/', views.NoteAutocomplete.as_view(model=Note), name='note_autocomplete'),
]

note_kfet/urls.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    # Dev so redirect to something random
    path('', RedirectView.as_view(pattern_name='note:transfer'), name='index'),

    # Include project routers
    path('note/', include('note.urls')),

    # Include Django Contrib and Core routers
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('member.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if "cas_server" in settings.INSTALLED_APPS:
    urlpatterns += [
        # Include CAS Server routers
        path('cas/', include('cas_server.urls', namespace="cas_server")),
    ]
if "cas" in settings.INSTALLED_APPS:
    from cas import views as cas_views
    urlpatterns += [
        # Include CAS Client routers
        path('accounts/login/cas/', cas_views.login, name='cas_login'),
        path('accounts/logout/cas/', cas_views.logout, name='cas_logout'),
       
    ]
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/note/forms.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from dal import autocomplete
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Alias
from .models import Transaction, TransactionTemplate


class AliasForm(forms.ModelForm):
    class Meta:
        model = Alias
        fields = ("name",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].label = False
        self.fields["name"].widget.attrs = {"placeholder": _('New Alias')}


class ImageForm(forms.Form):
    image = forms.ImageField(required=False,
                             label=_('select an image'),
                             help_text=_('Maximal size: 2MB'))
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())


class TransactionTemplateForm(forms.ModelForm):
    class Meta:
        model = TransactionTemplate
        fields = '__all__'

        # Le champ de destination est remplacé par un champ d'auto-complétion.
        # Quand des lettres sont tapées, une requête est envoyée sur l'API d'auto-complétion
        # et récupère les aliases valides
        # Pour force le type d'une note, il faut rajouter le paramètre :
        # forward=(forward.Const('TYPE', 'note_type') où TYPE est dans {user, club, special}
        widgets = {
            'destination':
                autocomplete.ModelSelect2(
                    url='note:note_autocomplete',
                    attrs={
                        'data-placeholder': 'Note ...',
                        'data-minimum-input-length': 1,
                    },
                ),
        }


class TransactionForm(forms.ModelForm):
    def save(self, commit=True):
        super().save(commit)

    def clean(self):
        """
        If the user has no right to transfer funds, then it will be the source of the transfer by default.
        Transactions between a note and the same note are not authorized.
        """

        cleaned_data = super().clean()
        if "source" not in cleaned_data:  # TODO Replace it with "if %user has no right to transfer funds"
            cleaned_data["source"] = self.user.note

        if cleaned_data["source"].pk == cleaned_data["destination"].pk:
            self.add_error("destination", _("Source and destination must be different."))

        return cleaned_data

    class Meta:
        model = Transaction
        fields = (
            'source',
            'destination',
            'reason',
            'amount',
        )

        # Voir ci-dessus
        widgets = {
            'source':
                autocomplete.ModelSelect2(
                    url='note:note_autocomplete',
                    attrs={
                        'data-placeholder': 'Note ...',
                        'data-minimum-input-length': 1,
                    },
                ),
            'destination':
                autocomplete.ModelSelect2(
                    url='note:note_autocomplete',
                    attrs={
                        'data-placeholder': 'Note ...',
                        'data-minimum-input-length': 1,
                    },
                ),
        }

apps/note/api/views.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from django.db.models import Q
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.filters import SearchFilter

from .serializers import NoteSerializer, NotePolymorphicSerializer, NoteClubSerializer, NoteSpecialSerializer, \
    NoteUserSerializer, AliasSerializer, \
    TemplateCategorySerializer, TransactionTemplateSerializer, TransactionPolymorphicSerializer
from ..models.notes import Note, NoteClub, NoteSpecial, NoteUser, Alias
from ..models.transactions import TransactionTemplate, Transaction, TemplateCategory


class NoteViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `Note` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/note/
    """
    queryset = Note.objects.all()
    serializer_class = NoteSerializer


class NoteClubViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `NoteClub` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/club/
    """
    queryset = NoteClub.objects.all()
    serializer_class = NoteClubSerializer


class NoteSpecialViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `NoteSpecial` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/special/
    """
    queryset = NoteSpecial.objects.all()
    serializer_class = NoteSpecialSerializer


class NoteUserViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `NoteUser` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/user/
    """
    queryset = NoteUser.objects.all()
    serializer_class = NoteUserSerializer


class NotePolymorphicViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `Note` objects (with polymorhism), serialize it to JSON with the given serializer,
    then render it on /api/note/note/
    """
    queryset = Note.objects.all()
    serializer_class = NotePolymorphicSerializer

    def get_queryset(self):
        """
        Parse query and apply filters.
        :return: The filtered set of requested notes
        """
        queryset = Note.objects.all()

        alias = self.request.query_params.get("alias", ".*")
        queryset = queryset.filter(
            Q(alias__name__regex="^" + alias)
            | Q(alias__normalized_name__regex="^" + alias.lower()))

        note_type = self.request.query_params.get("type", None)
        if note_type:
            types = str(note_type).lower()
            if "user" in types:
                queryset = queryset.filter(polymorphic_ctype__model="noteuser")
            elif "club" in types:
                queryset = queryset.filter(polymorphic_ctype__model="noteclub")
            elif "special" in types:
                queryset = queryset.filter(
                    polymorphic_ctype__model="notespecial")
            else:
                queryset = queryset.none()

        return queryset


class AliasViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `Alias` objects, serialize it to JSON with the given serializer,
    then render it on /api/aliases/
    """
    queryset = Alias.objects.all()
    serializer_class = AliasSerializer

    def get_queryset(self):
        """
        Parse query and apply filters.
        :return: The filtered set of requested aliases
        """

        queryset = Alias.objects.all()

        alias = self.request.query_params.get("alias", ".*")
        queryset = queryset.filter(
            Q(name__regex="^" + alias) | Q(normalized_name__regex="^" + alias.lower()))

        note_id = self.request.query_params.get("note", None)
        if note_id:
            queryset = queryset.filter(id=note_id)

        note_type = self.request.query_params.get("type", None)
        if note_type:
            types = str(note_type).lower()
            if "user" in types:
                queryset = queryset.filter(
                    note__polymorphic_ctype__model="noteuser")
            elif "club" in types:
                queryset = queryset.filter(
                    note__polymorphic_ctype__model="noteclub")
            elif "special" in types:
                queryset = queryset.filter(
                    note__polymorphic_ctype__model="notespecial")
            else:
                queryset = queryset.none()

        return queryset


class TemplateCategoryViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `TemplateCategory` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/transaction/category/
    """
    queryset = TemplateCategory.objects.all()
    serializer_class = TemplateCategorySerializer
    filter_backends = [SearchFilter]
    search_fields = ['$name', ]


class TransactionTemplateViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `TransactionTemplate` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/transaction/template/
    """
    queryset = TransactionTemplate.objects.all()
    serializer_class = TransactionTemplateSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['name', 'amount', 'display', 'category', ]


class TransactionViewSet(viewsets.ModelViewSet):
    """
    REST API View set.
    The djangorestframework plugin will get all `Transaction` objects, serialize it to JSON with the given serializer,
    then render it on /api/note/transaction/transaction/
    """
    queryset = Transaction.objects.all()
    serializer_class = TransactionPolymorphicSerializer
    filter_backends = [SearchFilter]
    search_fields = ['$reason', ]

apps/note/views.py
# Copyright (C) 2018-2020 by BDE ENS Paris-Saclay
# SPDX-License-Identifier: GPL-3.0-or-later

from dal import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, ListView, UpdateView
from django_tables2 import SingleTableView

from .forms import TransactionForm, TransactionTemplateForm
from .models import Transaction, TransactionTemplate, Alias
from .tables import HistoryTable


class TransactionCreate(LoginRequiredMixin, CreateView):
    """
    Show transfer page

    TODO: If user have sufficient rights, they can transfer from an other note
    """
    model = Transaction
    form_class = TransactionForm

    def get_context_data(self, **kwargs):
        """
        Add some context variables in template such as page title
        """
        context = super().get_context_data(**kwargs)
        context['title'] = _('Transfer money from your account '
                             'to one or others')

        context['no_cache'] = True

        return context

    def get_form(self, form_class=None):
        """
        If the user has no right to transfer funds, then it won't have the choice of the source of the transfer.
        """
        form = super().get_form(form_class)

        if False:  # TODO: fix it with "if %user has no right to transfer funds"
            del form.fields['source']
            form.user = self.request.user

        return form

    def get_success_url(self):
        return reverse('note:transfer')


class NoteAutocomplete(autocomplete.Select2QuerySetView):
    """
    Auto complete note by aliases
    """

    def get_queryset(self):
        """
        Quand une personne cherche un alias, une requête est envoyée sur l'API dédiée à l'auto-complétion.
        Cette fonction récupère la requête, et renvoie la liste filtrée des aliases.
        """
        #  Un utilisateur non connecté n'a accès à aucune information
        if not self.request.user.is_authenticated:
            return Alias.objects.none()

        qs = Alias.objects.all()

        # self.q est le paramètre de la recherche
        if self.q:
            qs = qs.filter(Q(name__regex="^" + self.q) | Q(normalized_name__regex="^" + Alias.normalize(self.q))) \
                .order_by('normalized_name').distinct()

        # Filtrage par type de note (user, club, special)
        note_type = self.forwarded.get("note_type", None)
        if note_type:
            types = str(note_type).lower()
            if "user" in types:
                qs = qs.filter(note__polymorphic_ctype__model="noteuser")
            elif "club" in types:
                qs = qs.filter(note__polymorphic_ctype__model="noteclub")
            elif "special" in types:
                qs = qs.filter(note__polymorphic_ctype__model="notespecial")
            else:
                qs = qs.none()

        return qs

    def get_result_label(self, result):
        # Gère l'affichage de l'alias dans la recherche
        res = result.name
        note_name = str(result.note)
        if res != note_name:
            res += " (aka. " + note_name + ")"
        return res

    def get_result_value(self, result):
        # Le résultat renvoyé doit être l'identifiant de la note, et non de l'alias
        return str(result.note.pk)


class TransactionTemplateCreateView(LoginRequiredMixin, CreateView):
    """
    Create TransactionTemplate
    """
    model = TransactionTemplate
    form_class = TransactionTemplateForm


class TransactionTemplateListView(LoginRequiredMixin, ListView):
    """
    List TransactionsTemplates
    """
    model = TransactionTemplate
    form_class = TransactionTemplateForm


class TransactionTemplateUpdateView(LoginRequiredMixin, UpdateView):
    """
    """
    model = TransactionTemplate
    form_class = TransactionTemplateForm


class ConsoView(LoginRequiredMixin, SingleTableView):
    """
    Consume
    """
    model = Transaction
    template_name = "note/conso_form.html"

    # Transaction history table
    table_class = HistoryTable
    table_pagination = {"per_page": 10}

    def get_context_data(self, **kwargs):
        """
        Add some context variables in template such as page title
        """
        context = super().get_context_data(**kwargs)
        context['transaction_templates'] = TransactionTemplate.objects.filter(display=True) \
            .order_by('category')
        context['title'] = _("Consumptions")

        # select2 compatibility
        context['no_cache'] = True

        return context

templates/note/conso_form.html
{% extends "base.html" %}

{% load i18n static pretty_money django_tables2 %}

{# Remove page title #}
{% block contenttitle %}{% endblock %}

{% block content %}
    <div class="row mt-4">
        <div class="col-sm-5 col-md-4">
            <div class="row">
                {# User details column #}
                <div class="col-xl-5">
                    <div class="card border-success shadow mb-4">
                        <img src="https://perso.crans.org/erdnaxe/site-crans/img/logo.svg"
                            alt="" class="img-fluid rounded mx-auto d-block">
                        <div class="card-body text-center">
                            Paquito (aka. PAC) : -230 €
                        </div>
                    </div>
                </div>

                {# User selection column #}
                <div class="col-xl-7">
                    <div class="card border-success shadow mb-4">
                        <div class="card-header">
                            <p class="card-text font-weight-bold">
                                Sélection des émitteurs
                            </p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item py-1 d-flex justify-content-between align-items-center">
                                Cras justo odio
                                <span class="badge badge-dark badge-pill">14</span>
                            </li>
                            <li class="list-group-item py-1 d-flex justify-content-between align-items-center">
                                Dapibus ac facilisis in
                                <span class="badge badge-dark badge-pill">1</span>
                            </li>
                        </ul>
                        <div class="card-body">
                            TODO: reimplement select2 here in JS
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {# Buttons column #}
        <div class="col-sm-7 col-md-8">
            {# Show last used buttons #}
            <div class="card shadow mb-4">
                <div class="card-body text-nowrap" style="overflow:auto hidden">
                    <p class="card-text text-muted font-weight-light font-italic">
                        Les boutons les plus utilisés s'afficheront ici.
                    </p>
                </div>
            </div>

            {# Regroup buttons under categories #}
            {% regroup transaction_templates by template_type as template_types %}

            <div class="card border-primary text-center shadow mb-4">
                {# Tabs for button categories #}
                <div class="card-header">
                    <ul class="nav nav-tabs nav-fill card-header-tabs">
                        {% for template_type in template_types %}
                            <li class="nav-item">
                                <a class="nav-link font-weight-bold" data-toggle="tab" href="#{{ template_type.grouper|slugify }}">
                                    {{ template_type.grouper }}
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                {# Tabs content #}
                <div class="card-body">
                    <div class="tab-content">
                        {% for template_type in template_types %}
                            <div class="tab-pane" id="{{ template_type.grouper|slugify }}">
                                <div class="d-inline-flex flex-wrap justify-content-center">
                                    {% for button in template_type.list %}
                                        <button class="btn btn-outline-dark rounded-0 flex-fill"
                                                name="button" value="{{ button.name }}">
                                            {{ button.name }} ({{ button.amount | pretty_money }})
                                        </button>
                                    {% endfor %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                {# Mode switch #}
                <div class="card-footer border-primary">
                    <a class="btn btn-sm btn-secondary float-left" href="{% url 'note:template_list' %}">
                        <i class="fa fa-edit"></i> Éditer
                    </a>
                    <div class="btn-group btn-group-toggle float-right" data-toggle="buttons">
                        <label class="btn btn-sm btn-outline-primary active">
                            <input type="radio" name="options" id="option1" checked>
                            Consomations simples
                        </label>
                        <label class="btn btn-sm btn-outline-primary">
                            <input type="radio" name="options" id="option2">
                            Consomations doubles
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header">
            <p class="card-text font-weight-bold">
                Historique des transactions récentes
            </p>
        </div>
        {% render_table table %}
    </div>
{% endblock %}

{% block extracss %}
    <style>
        .select2-container{
            max-width: 100%;
            min-width: 100%;
        }
    </style>
{% endblock %}

{% block extrajavascript %}
    <script type="text/javascript">
        $(document).ready(function() {
            // If hash of a category in the URL, then select this category
            // else select the first one
            if (location.hash) {
                $("a[href='" + location.hash + "']").tab("show");
            } else {
                $("a[data-toggle='tab']").first().tab("show");
            }

            // When selecting a category, change URL
            $(document.body).on("click", "a[data-toggle='tab']", function(event) {
                location.hash = this.getAttribute("href");
            });
        });
    </script>
{% endblock %}

templates/note/transaction_form.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-2.0-or-later
{% endcomment %}

{% load i18n static %}

{% block content %}
    <form method="post" onsubmit="window.onbeforeunload=null">{% csrf_token %}
        {% if form.non_field_errors %}
            <p class="errornote">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </p>
        {% endif %}
        <fieldset class="module aligned">
            {% for field in form %}
                <div class="form-row{% if field.errors %} errors{% endif %}">
                    {{ field.errors }}
                    <div>
                        {{ field.label_tag }}
                        {% if field.is_readonly %}
                            <div class="readonly">{{ field.contents }}</div>
                        {% else %}
                            {{ field }}
                        {% endif %}
                        {% if field.field.help_text %}
                            <div class="help">{{ field.field.help_text|safe }}</div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </fieldset>
        <input type="submit" value="{% trans 'Transfer' %}">
    </form>
{% endblock %}

templates/note/transactiontemplate_form.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'note:template_list' %}">{% trans "Buttons list" %}</a></p>
<form method="post">
{% csrf_token %}
{{form|crispy}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

templates/note/transactiontemplate_list.html
{% extends "base.html" %}
{% load pretty_money %}
{% block content %}

<table class="table">
<tr>
<td>ID</td><td>Nom</td>
    <td>Destinataire</td>
    <td>Montant</td>
    <td>Catégorie</td>
</tr>
{% for object in object_list %}
<tr>
    <td>{{object.pk}}</td>
    <td><a href="{{object.get_absolute_url}}">{{ object.name }}</a></td>
    <td>{{ object.destination }}</td>
    <td>{{ object.amount | pretty_money }}</td>
    <td>{{ object.template_type }}</td>
</tr>
{% endfor %}
</table>
<a class="btn btn-primary" href="{% url 'note:template_create' %}">Créer un bouton</a>
{% endblock %}